frame_id:
  fixed: $(arg robot_namespace)/map_locus
  base: $(arg robot_namespace)/base_link
  imu: $(arg robot_namespace)/vn100
  bd_odometry: $(arg robot_namespace)/fixed_map_odom
  artifacts_in_global: true

frame_conversions: 
  b_convert_imu_to_base_link_frame: true